### ISSUE TITLE
Panic in serviceerror.FromStatus

### ISSUE THREAD

**Issue by mfateev** [temporalio/temporal-go-sdk#104]
It looks like the service doesn't include NotFound into details:

<img width="511" alt="Screen Shot 2020-04-19 at 7 11 10 PM" src="https://user-images.githubusercontent.com/1463622/79707544-b2bf0580-8271-11ea-80f5-5d27ca6a6e2c.png">

```
GOROOT=/usr/local/go #gosetup
GOPATH=/Users/maxim/go #gosetup
/usr/local/go/bin/go build -o /private/var/folders/q2/4s0fwr9s30zbg8qr8tw8y_440000gn/T/___go_build_main_go__1_ /Users/maxim/temporal/temporal-go-samples/helloworld/starter/main.go #gosetup
/private/var/folders/q2/4s0fwr9s30zbg8qr8tw8y_440000gn/T/___go_build_main_go__1_ #gosetup
panic: interface conversion: interface {} is nil, not *failure.NotFound

goroutine 1 [running]:
go.temporal.io/temporal-proto/serviceerror.FromStatus(0xc000010050, 0xc0000ee370, 0xc000010050)
        /Users/maxim/go/pkg/mod/go.temporal.io/temporal-proto@v0.20.22/serviceerror/convert.go:94 +0x1d29
go.temporal.io/temporal/internal.errorInterceptor(0x19da6c0, 0xc000146ba0, 0x18f216f, 0x37, 0x18b8ec0, 0xc0001569a0, 0x188d840, 0xc0003cc100, 0xc0003be700, 0x1906e70, ...)
        /Users/maxim/go/pkg/mod/go.temporal.io/temporal@v0.21.1-0.20200414162012-9592ebc6a1f7/internal/grpc_dialer.go:72 +0xef
google.golang.org/grpc.getChainUnaryInvoker.func1(0x19da6c0, 0xc000146ba0, 0x18f216f, 0x37, 0x18b8ec0, 0xc0001569a0, 0x188d840, 0xc0003cc100, 0xc0003be700, 0x0, ...)
        /Users/maxim/go/pkg/mod/google.golang.org/grpc@v1.28.1/clientconn.go:359 +0x151
go.temporal.io/temporal/internal/common/metrics.NewScopeInterceptor.func1(0x19da6c0, 0xc000146ba0, 0x18f216f, 0x37, 0x18b8ec0, 0xc0001569a0, 0x188d840, 0xc0003cc100, 0xc0003be700, 0xc0003251a0, ...)
        /Users/maxim/go/pkg/mod/go.temporal.io/temporal@v0.21.1-0.20200414162012-9592ebc6a1f7/internal/common/metrics/interceptor.go:50 +0x108
google.golang.org/grpc.chainUnaryClientInterceptors.func1(0x19da6c0, 0xc000146ba0, 0x18f216f, 0x37, 0x18b8ec0, 0xc0001569a0, 0x188d840, 0xc0003cc100, 0xc0003be700, 0x1906e70, ...)
        /Users/maxim/go/pkg/mod/google.golang.org/grpc@v1.28.1/clientconn.go:347 +0x12f
google.golang.org/grpc.(*ClientConn).Invoke(0xc0003be700, 0x19da6c0, 0xc000146ba0, 0x18f216f, 0x37, 0x18b8ec0, 0xc0001569a0, 0x188d840, 0xc0003cc100, 0x0, ...)
        /Users/maxim/go/pkg/mod/google.golang.org/grpc@v1.28.1/call.go:35 +0x109
go.temporal.io/temporal-proto/workflowservice.(*workflowServiceClient).StartWorkflowExecution(0xc00014a390, 0x19da6c0, 0xc000146ba0, 0xc0001569a0, 0x0, 0x0, 0x0, 0xc0003cc0f0, 0x49d5e6031b5e0, 0x1f4c440)
        /Users/maxim/go/pkg/mod/go.temporal.io/temporal-proto@v0.20.22/workflowservice/service.pb.go:337 +0xcf
go.temporal.io/temporal/internal.(*WorkflowClient).StartWorkflow.func1(0x0, 0x0)
        /Users/maxim/go/pkg/mod/go.temporal.io/temporal@v0.21.1-0.20200414162012-9592ebc6a1f7/internal/internal_workflow_client.go:229 +0x112
go.temporal.io/temporal/internal/common/backoff.Retry(0x19da680, 0xc0000ce000, 0xc0002077d0, 0x19c4e80, 0xc00020a2a0, 0x1906be8, 0x1f4b6a0, 0xc000134ec0)
        /Users/maxim/go/pkg/mod/go.temporal.io/temporal@v0.21.1-0.20200414162012-9592ebc6a1f7/internal/common/backoff/retry.go:102 +0xfb
go.temporal.io/temporal/internal.(*WorkflowClient).StartWorkflow(0xc0001fe6c0, 0x19da680, 0xc0000ce000, 0x18daebc, 0x16, 0x18da54b, 0x15, 0xdf8475800, 0x0, 0x0, ...)
        /Users/maxim/go/pkg/mod/go.temporal.io/temporal@v0.21.1-0.20200414162012-9592ebc6a1f7/internal/internal_workflow_client.go:223 +0x727
go.temporal.io/temporal/internal.(*WorkflowClient).ExecuteWorkflow(0xc0001fe6c0, 0x19da680, 0xc0000ce000, 0x18daebc, 0x16, 0x18da54b, 0x15, 0xdf8475800, 0x0, 0x0, ...)
        /Users/maxim/go/pkg/mod/go.temporal.io/temporal@v0.21.1-0.20200414162012-9592ebc6a1f7/internal/internal_workflow_client.go:263 +0xc7
main.main()
        /Users/maxim/temporal/temporal-go-samples/helloworld/starter/main.go:32 +0x457

Process finished with exit code 2

```
I'm running service as of 729c8e458ac0fd3bf6d6f1ad509b2e20300e2bd9

**Comment by alexshtin** [comment]
You updated `go.temporal.io/temporal-proto` to 0.20.22 a little bit earlier. I made a change there which is intended to be used for latest merge from Cadence. Please roll back to 0.20.21 and it should work fine. I will update SDK later, when server is ready.

**Comment by alexshtin** [comment]
Fixed by https://github.com/temporalio/temporal-proto-go/commit/fd32111876d6ed73c2771107460783b09fb36a6f
